version: '3'

services:
  app:
    image: bis200705/docker-basics-app
    container_name: docker-basics-app
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - docker-basics-custom-net
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./logs:/usr/app/logs
    environment:
      PORT: ${PORT}

  postgres:
    image: bis200705/docker-basics-postgres
    container_name: docker-basics-postgres
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - docker-basics-custom-net
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

networks:
  docker-basics-custom-net:
    driver: bridge

volumes:
  logs:
  db: